### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by himdel** [patternfly/patternfly-timeline#28]
Hey,
I've created a `patternfly-timeline@1.0.2` npm package, but I'm guessing, going forward, you'd like to maintain it..

So please tell me to whom and I'll transfer the ownership..

**Comment by himdel** [comment]
@dgutride any progress on this one please?

I've just updated the npm package to 1.0.3.. (ManageIQ is abandoning bower very soon..)

**Comment by dgutride** [comment]
Package owner added to @dgutride - closing
