### ISSUE TITLE
Precompiling /dist contesnts prior to publishing new versions on npm

### ISSUE THREAD

**Issue by AllenBW** [patternfly/patternfly-timeline#36]
Might not be an issue, but given the case one might want to use the built version of patternfly-timeline, presently, when adding via npm, `/dist` does not exist.  Should the lib be build for each version? @jeff-phillips-18 @dgutride 

Kinda related to this issue https://github.com/patternfly/patternfly-timeline/issues/23

**Comment by dgutride** [comment]
@allenbw - the last release was done and missed this, we will rerelease 1.0.6 from the dist branch - thanks!

**Comment by dgutride** [comment]
@AllenBW - release 1.0.6 has been published to NPM which includes the dist - let me know if you have any other issues.

**Comment by AllenBW** [comment]
@dgutride YA ROCK thanks!!! 👨‍🎤

**Comment by AllenBW** [comment]
@dgutride I spoke too soon, just checked the release, appropriately advertised as version 1.0.6, but still no dist folder :(
<img width="855" alt="screen shot 2017-05-10 at 10 37 06 am" src="https://cloud.githubusercontent.com/assets/6640236/25904307/db32bae8-356c-11e7-96cb-7105721bbb0b.png">

**Comment by dgutride** [comment]
@AllenBW  - ugh, sorry for the confusion, we needed to add an npmignore file to get this working correctly.  1.0.7 contains the dist files now.  I think up until now, everybody was using bower which was why this wasn't noticed.

**Comment by AllenBW** [comment]
WOOH THERE IT IS! <3
