### ISSUE TITLE
Adding/removing drop dynamically

### ISSUE THREAD

**Issue by aureq** [patternfly/patternfly-timeline#47]
Hi,

I'm looking for a way to dynamically add/remove drops from a specific timeline on a chart. I initially tried to use the "display" property, but obviously it doesn't apply to drops. Despite searching for quite  some time now, I haven't been able to find a way to do it. Could someone point me in the right direction? What would be the best way to implement this?

Thanks

**Comment by cshinn** [comment]
The timeline is rendered as a big SVG, so your best bet without modifying much is probably to add or remove the item from the data object that gets passed in and then redraw the chart

**Comment by aureq** [comment]
Thank you @cshinn. Yes, this is what I figured out in between. But I lost so much time because of array shallow copies... Well, that's a good learning experience though.
